exclude = [
  "@ref",
  "@[Cc]ite.*",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://theogf.github.io/Narcissus.jl/stable/?$",

  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
